# **TikTok Project**
**Course 2 - Get Started with Python**

Welcome to the TikTok Project!

You have just started as a data professional at TikTok.

The team is still in the early stages of the project. You have received notice that TikTok's leadership team has approved the project proposal. To gain clear insights to prepare for a claims classification model, TikTok's provided data must be examined to begin the process of exploratory data analysis (EDA).

A notebook was structured and prepared to help you in this project. Please complete the following questions.

# **Course 2 End-of-course project: Inspect and analyze data**

In this activity, you will examine data provided and prepare it for analysis.
<br/>

**The purpose** of this project is to investigate and understand the data provided. This activity will:

1.   Acquaint you with the data

2.   Compile summary information about the data

3.   Begin the process of EDA and reveal insights contained in the data

4.   Prepare you for more in-depth EDA, hypothesis testing, and statistical analysis

**The goal** is to construct a dataframe in Python, perform a cursory inspection of the provided dataset, and inform TikTok data team members of your findings.
<br/>
*This activity has three parts:*

**Part 1:** Understand the situation
* How can you best prepare to understand and organize the provided TikTok information?

**Part 2:** Understand the data

* Create a pandas dataframe for data learning and future exploratory data analysis (EDA) and statistical activities

* Compile summary information about the data to inform next steps

**Part 3:** Understand the variables

* Use insights from your examination of the summary data to guide deeper investigation into variables

<br/>

To complete the activity, follow the instructions and answer the questions below. Then, you will us your responses to these questions and the questions included in the Course 2 PACE Strategy Document to create an executive summary.

Be sure to complete this activity before moving on to Course 3. You can assess your work by comparing the results to a completed exemplar after completing the end-of-course project.

# **Identify data types and compile summary information**

Throughout these project notebooks, you'll see references to the problem-solving framework PACE. The following notebook components are labeled with the respective PACE stage: Plan, Analyze, Construct, and Execute.

# **PACE stages**

<img src="images/Pace.png" width="100" height="100" align=left>

   *        [Plan](#scrollTo=psz51YkZVwtN&line=3&uniqifier=1)
   *        [Analyze](#scrollTo=mA7Mz_SnI8km&line=4&uniqifier=1)
   *        [Construct](#scrollTo=Lca9c8XON8lc&line=2&uniqifier=1)
   *        [Execute](#scrollTo=401PgchTPr4E&line=2&uniqifier=1)

<img src="images/Plan.png" width="100" height="100" align=left>


## **PACE: Plan**

Consider the questions in your PACE Strategy Document and those below to craft your response:

### **Task 1. Understand the situation**

*   How can you best prepare to understand and organize the provided information?


*Begin by exploring your dataset and consider reviewing the Data Dictionary.*

==> ENTER YOUR RESPONSE HERE

<img src="images/Analyze.png" width="100" height="100" align=left>

## **PACE: Analyze**

Consider the questions in your PACE Strategy Document to reflect on the Analyze stage.

### **Task 2a. Imports and data loading**

Start by importing the packages that you will need to load and explore the dataset. Make sure to use the following import statements:
*   `import pandas as pd`

*   `import numpy as np`

In [1]:
# Import packages
import pandas as pd
import numpy as np

Then, load the dataset into a dataframe. Creating a dataframe will help you conduct data manipulation, exploratory data analysis (EDA), and statistical activities.

**Note:** As shown in this cell, the dataset has been automatically loaded in for you. You do not need to download the .csv file, or provide more code, in order to access the dataset and proceed with this lab. Please continue with this activity by completing the following instructions.

In [65]:
# Load dataset into dataframe
data = pd.read_csv("tiktok_dataset.csv")

### **Task 2b. Understand the data - Inspect the data**

View and inspect summary information about the dataframe by **coding the following:**

1. `data.head(10)`
2. `data.info()`
3. `data.describe()`

*Consider the following questions:*

**Question 1:** When reviewing the first few rows of the dataframe, what do you observe about the data? What does each row represent?

**Question 2:** When reviewing the `data.info()` output, what do you notice about the different variables? Are there any null values? Are all of the variables numeric? Does anything else stand out?

**Question 3:** When reviewing the `data.describe()` output, what do you notice about the distributions of each variable? Are there any questionable values? Does it seem that there are outlier values?

In [3]:
# Display and examine the first ten rows of the dataframe
data.head(10)

,#,claim_status,video_id,video_duration_sec,video_transcription_text,verified_status,author_ban_status,video_view_count,video_like_count,video_share_count,video_download_count,video_comment_count
0,1,claim,7017666017,59,someone shared with me that drone deliveries a...,not verified,under review,343296.0,19425.0,241.0,1.0,0.0
1,2,claim,4014381136,32,someone shared with me that there are more mic...,not verified,active,140877.0,77355.0,19034.0,1161.0,684.0
2,3,claim,9859838091,31,someone shared with me that american industria...,not verified,active,902185.0,97690.0,2858.0,833.0,329.0
3,4,claim,1866847991,25,someone shared with me that the metro of st. p...,not verified,active,437506.0,239954.0,34812.0,1234.0,584.0
4,5,claim,7105231098,19,someone shared with me that the number of busi...,not verified,active,56167.0,34987.0,4110.0,547.0,152.0
5,6,claim,8972200955,35,someone shared with me that gross domestic pro...,not verified,under review,336647.0,175546.0,62303.0,4293.0,1857.0
6,7,claim,4958886992,16,someone shared with me that elvis presley has ...,not verified,active,750345.0,486192.0,193911.0,8616.0,5446.0
7,8,claim,2270982263,41,someone shared with me that the best selling s...,not verified,active,547532.0,1072.0,50.0,22.0,11.0
8,9,claim,5235769692,50,someone shared with me that about half of the ...,not verified,active,24819.0,10160.0,1050.0,53.0,27.0
9,10,claim,4660861094,45,someone shared with me that it would take a 50...,verified,active,931587.0,171051.0,67739.0,4104.0,2540.0

In [4]:
# Get summary info
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19382 entries, 0 to 19381
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   #                         19382 non-null  int64
 1   claim_status              19084 non-null  object
 2   video_id                  19382 non-null  int64
 3   video_duration_sec        19382 non-null  int64
 4   video_transcription_text  19084 non-null  object
 5   verified_status           19382 non-null  object
 6   author_ban_status         19382 non-null  object
 7   video_view_count          19084 non-null  float64
 8   video_like_count          19084 non-null  float64
 9   video_share_count         19084 non-null  float64
 10  video_download_count      19084 non-null  float64
 11  video_comment_count       19084 non-null  float64
dtypes: float64(5), int64(3), object(4)
memory usage: 1.8+ MB

In [5]:
# Get summary statistics
data.describe()

,#,video_id,video_duration_sec,video_view_count,video_like_count,video_share_count,video_download_count,video_comment_count
count,19382.000000,1.938200e+04,19382.000000,19084.000000,19084.000000,19084.000000,19084.000000,19084.000000
mean,9691.500000,5.627454e+09,32.421732,254708.558688,84304.636030,16735.248323,1049.429627,349.312146
std,5595.245794,2.536440e+09,16.229967,322893.280814,133420.546814,32036.174350,2004.299894,799.638865
min,1.000000,1.234959e+09,5.000000,20.000000,0.000000,0.000000,0.000000,0.000000
25%,4846.250000,3.430417e+09,18.000000,4942.500000,810.750000,115.000000,7.000000,1.000000
50%,9691.500000,5.618664e+09,32.000000,9954.500000,3403.500000,717.000000,46.000000,9.000000
75%,14536.750000,7.843960e+09,47.000000,504327.000000,125020.000000,18222.000000,1156.250000,292.000000
max,19382.000000,9.999873e+09,60.000000,999817.000000,657830.000000,256130.000000,14994.000000,9599.000000

1) Every video has a claim status, with its duration recorded, verified status, and other importand details about the qualifications of the video. We also see that there is a verified column that shows whether the claim status has been verified or not. This could be useful for training ML models later on.

2) After running the .info() method I see there are no null values and that there are a total of 12 columns. Three of these columns are objects because they are primarily string which are indicative of the status of the video. The remaining 6 columns have important data about the length, number of views, number of comments, number of likes and so on.

3) After seeing some of the important statistics of the data Im a surprised to see the magnitude of the max of multiple columns such at the "view count", "like count" and "share count"

### **Task 2c. Understand the data - Investigate the variables**

In this phase, you will begin to investigate the variables more closely to better understand them.

You know from the project proposal that the ultimate objective is to use machine learning to classify videos as either claims or opinions. A good first step towards understanding the data might therefore be examining the `claim_status` variable. Begin by determining how many videos there are for each different claim status.

In [13]:
# What are the different values for claim status and how many of each are in the data?
# Use boolean masking to filter the videos based on claim status
claims = data[data['claim_status'] == "claim"]
opinions = data[data['claim_status'] == "opinion"]
others = data[(data["claim_status"] != "opinion") & (data['claim_status'] != "claim")]

print("Number of videos categorized as claims:",len(claims))
print("Number of videos categorized as opinions:",len(opinions))
print("Total # of categorized videos:",len(opinions)+len(claims))

print("Number of videos without a claim staus:",len(others))

Number of videos categorized as claims: 9608
Number of videos categorized as opinions: 9476
Total # of categorized videos: 19084
Number of videos without a claim staus: 298

**Question:** What do you notice about the values shown?

The sum of the lengths of the categorized videos does not match the length of the dataframe itself. I appears there are some videos who have no claim status, and insted have NaN values instead.

Next, examine the engagement trends associated with each different claim status.

Start by using Boolean masking to filter the data according to claim status, then calculate the mean and median view counts for each claim status.

In [29]:
# Create masks based on claim status
claim_mask = data['claim_status'] == "claim"
opinion_mask = data['claim_status'] == "opinion"

In [31]:
# Columns used to quantify engagement (video_duration_sec) (video_view_count) (video_like_count) (video_share_count)
# (video_download_count) (video_comment_count)

# Mask the video duration
C_durations = data[claim_mask]['video_duration_sec']
O_durations = data[opinion_mask]['video_duration_sec']

# Mask the view count
C_views = data[claim_mask]['video_view_count']
O_views = data[opinion_mask]['video_view_count']

# Mask the like count
C_likes = data[claim_mask]['video_like_count']
O_likes = data[opinion_mask]['video_like_count']

# Mask the share count
C_shares = data[claim_mask]['video_share_count']
O_shares = data[opinion_mask]['video_share_count']

# Mask the download count
C_downloads = data[claim_mask]['video_download_count']
O_downloads = data[opinion_mask]['video_download_count']

# Mask comment count
C_comments = data[claim_mask]['video_comment_count']
O_comments = data[opinion_mask]['video_comment_count']

In [36]:
# What is the average view count of videos with "claim" status?
# What is the average view count of videos with "opinion" status?
print("Claim Videos Mean View Count")
print(round(C_views.mean(),2),"sec \n")
print("Claim Videos Median View Count")
print(round(C_views.median(),2),"sec \n")
print("Opinion Videos Mean View Count")
print(round(O_views.mean(),2),"sec \n")
print("Opinion Videos Median View Count")
print(round(O_views.median(),2),"sec \n")

Claim Videos Mean View Count
501029.45 sec

Claim Videos Median View Count
501555.0 sec

Opinion Videos Mean View Count
4956.43 sec

Opinion Videos Median View Count
4953.0 sec

**Question:** What do you notice about the mean and media within each claim category?

**Answer:** I notice that the mean and the median are very close to one another. This could be an indication of a very symmetric distribution with minimal outliers.

Now, examine trends associated with the ban status of the author.

Use `groupby()` to calculate how many videos there are for each combination of categories of claim status and author ban status.

In [44]:
# Get counts for each group combination of claim status and author ban status
# Group by ban status and count how many videos correspond to each category
print("CLAIMS")
claims.groupby(['author_ban_status']).count()

CLAIMS

,#,claim_status,video_id,video_duration_sec,video_transcription_text,verified_status,video_view_count,video_like_count,video_share_count,video_download_count,video_comment_count
author_ban_status,,,,,,,,,,,
active,6566,6566,6566,6566,6566,6566,6566,6566,6566,6566,6566
banned,1439,1439,1439,1439,1439,1439,1439,1439,1439,1439,1439
under review,1603,1603,1603,1603,1603,1603,1603,1603,1603,1603,1603

In [45]:
print("Opinions")
opinions.groupby(['author_ban_status']).count()

Opinions

,#,claim_status,video_id,video_duration_sec,video_transcription_text,verified_status,video_view_count,video_like_count,video_share_count,video_download_count,video_comment_count
author_ban_status,,,,,,,,,,,
active,8817,8817,8817,8817,8817,8817,8817,8817,8817,8817,8817
banned,196,196,196,196,196,196,196,196,196,196,196
under review,463,463,463,463,463,463,463,463,463,463,463

**Question:** What do you notice about the number of claims videos with banned authors? Why might this relationship occur?

**Answer:** There are far more banned authors under the claim category than under the opinion category. This could be indication of a lot of misinformation being presented as claims that are not factual and thus can be harmful for society. As oposed to an opinion where its more subjective to the eyes of the public.

Continue investigating engagement levels, now focusing on `author_ban_status`.

Calculate the median video share count of each author ban status.

In [71]:
# Create masks for each author_ban_status to filter dataframe
banned_mask = data['author_ban_status'] == 'banned'
active_mask = data['author_ban_status'] == 'active'
under_review_mask = data['author_ban_status'] == 'under review'

In [73]:
# What's the median video share count of each author ban status?
B_median = data[banned_mask]['video_share_count'].median()
A_median = data[active_mask]['video_share_count'].median()
U_median = data[under_review_mask]['video_share_count'].median()

# Print results
print("Share count median for banned authors:",round(B_median,2),"\n")
print("Share count median for active authors:",round(A_median,2),"\n")
print("Share count median for under review authors:",round(U_median,2),"\n")

Share count median for banned authors: 14468.0

Share count median for active authors: 437.0

Share count median for under review authors: 9444.0

**Question:** What do you notice about the share count of banned authors, compared to that of active authors? Explore this in more depth.

**Answer:** The share count for banned authers is significantly higher than the share count of active authors. The diffence is close to 2 orders of magnitude. This means that most videos from banned authors went viral and led to them getting banned from the plataform.

Use `groupby()` to group the data by `author_ban_status`, then use `agg()` to get the count, mean, and median of each of the following columns:
* `video_view_count`
* `video_like_count`
* `video_share_count`

Remember, the argument for the `agg()` function is a dictionary whose keys are columns. The values for each column are a list of the calculations you want to perform.

In [75]:
# Group by dataframe by author_ban_status
authors_mean = data.groupby(['author_ban_status']).agg(['mean','median'])
authors_mean

C:\Users\patri\AppData\Local\Temp\ipykernel_15484\1608010742.py:2: FutureWarning: ['claim_status', 'video_transcription_text', 'verified_status'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  authors_mean = data.groupby(['author_ban_status']).agg(['mean','median'])

                              #               video_id                \
                           mean   median          mean        median
author_ban_status
active             10439.763136  10966.0  5.636678e+09  5.624036e+09
banned              5921.090299   5304.0  5.612067e+09  5.563176e+09
under review        7027.873077   6175.5  5.570120e+09  5.607722e+09

                  video_duration_sec        video_view_count            \
                                mean median             mean    median
author_ban_status
active                     32.546383   33.0    215927.039524    8616.0
banned                     32.346553   32.0    445845.439144  448201.0
under review               31.542308   31.0    392204.836399  365245.5

                  video_like_count           video_share_count           \
                              mean    median              mean   median
author_ban_status
active                71036.533836    2222.0      14111.466164    437.0
banned               153017.236697  105573.0      29998.942508  14468.0
under review         128718.050339   71204.5      25774.696999   9444.0

                  video_download_count        video_comment_count
                                  mean median                mean median
author_ban_status
active                      882.276344   28.0          295.134499    5.0
banned                     1886.296024  892.0          614.956575  209.0
under review               1631.734753  610.5          542.480639  136.5

**Question:** What do you notice about the number of views, likes, and shares for banned authors compared to active authors?

**Answer:** The results of using .agg on the dataframe show that there is significant difference between the mean and median of 'views' 'likes' and 'shares'. For almost all categories of 'authors_status' with the exception of the 'banned' authors in the 'views' category. Other than that section we can safely assume that the overall distribution of these sections are highly skewd. From experience when dealing with a skewd distribution it is more reliable to use the median instead of the mean as this quantity does no fluctuate as much due to the presence of outliers.

Now, create three new columns to help better understand engagement rates:
* `likes_per_view`: represents the number of likes divided by the number of views for each video
* `comments_per_view`: represents the number of comments divided by the number of views for each video
* `shares_per_view`: represents the number of shares divided by the number of views for each video

In [84]:
# Create a likes_per_view column
data['likes_per_view'] = data['video_like_count']/data['video_view_count']

# Create a comments_per_view column
data['comments_per_view'] = data["video_comment_count"] / data['video_view_count']

# Create a shares_per_view column
data['shares_per_view'] = data['video_share_count'] / data['video_view_count']

data

,#,claim_status,video_id,video_duration_sec,video_transcription_text,verified_status,author_ban_status,video_view_count,video_like_count,video_share_count,video_download_count,video_comment_count,likes_per_view,comments_per_view,shares_per_view
0,1,claim,7017666017,59,someone shared with me that drone deliveries a...,not verified,under review,343296.0,19425.0,241.0,1.0,0.0,0.056584,0.000000,0.000702
1,2,claim,4014381136,32,someone shared with me that there are more mic...,not verified,active,140877.0,77355.0,19034.0,1161.0,684.0,0.549096,0.004855,0.135111
2,3,claim,9859838091,31,someone shared with me that american industria...,not verified,active,902185.0,97690.0,2858.0,833.0,329.0,0.108282,0.000365,0.003168
3,4,claim,1866847991,25,someone shared with me that the metro of st. p...,not verified,active,437506.0,239954.0,34812.0,1234.0,584.0,0.548459,0.001335,0.079569
4,5,claim,7105231098,19,someone shared with me that the number of busi...,not verified,active,56167.0,34987.0,4110.0,547.0,152.0,0.622910,0.002706,0.073175
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19377,19378,NaN,7578226840,21,NaN,not verified,active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19378,19379,NaN,6079236179,53,NaN,not verified,active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19379,19380,NaN,2565539685,10,NaN,verified,under review,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19380,19381,NaN,2969178540,24,NaN,not verified,active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19381,19382,NaN,8132759688,13,NaN,not verified,active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Use `groupby()` to compile the information in each of the three newly created columns for each combination of categories of claim status and author ban status, then use `agg()` to calculate the count, the mean, and the median of each group.

In [87]:
# Group by claim status
data.groupby(['claim_status','author_ban_status']).agg(['mean','median'])

C:\Users\patri\AppData\Local\Temp\ipykernel_15484\1207800880.py:2: FutureWarning: ['video_transcription_text', 'verified_status'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  data.groupby(['claim_status','author_ban_status']).agg(['mean','median'])

                                           #               video_id  \
                                        mean   median          mean
claim_status author_ban_status
claim        active              4826.710326   4843.5  5.647627e+09
             banned              4704.156359   4695.0  5.562323e+09
             under review        4803.602620   4755.0  5.602155e+09
opinion      active             14340.511966  14349.0  5.622337e+09
             banned             14584.275510  14761.0  5.996526e+09
             under review       14359.874730  14176.0  5.464840e+09

                                             video_duration_sec         \
                                      median               mean median
claim_status author_ban_status
claim        active             5.625380e+09          32.633567   33.0
             banned             5.534796e+09          32.370396   32.0
             under review       5.635166e+09          31.990643   32.0
opinion      active             5.606485e+09          32.489395   33.0
             banned             6.258346e+09          31.979592   32.0
             under review       5.417117e+09          30.053996   28.0

                               video_view_count           video_like_count  \
                                           mean    median             mean
claim_status author_ban_status
claim        active               499221.733171  499500.5    164960.302924
             banned               505907.917304  512572.0    173719.102849
             under review         504054.640674  500774.0    165566.954460
opinion      active                 4958.120563    4958.0      1091.714982
             banned                 4876.530612    5083.5      1027.515306
             under review           4958.105832    4884.0      1139.663067

                                          ... video_download_count          \
                                  median  ...                 mean  median
claim_status author_ban_status            ...
claim        active             121943.0  ...          2048.669510  1124.5
             banned             132044.0  ...          2141.457957  1204.0
             under review       125882.0  ...          2098.931379  1153.0
opinion      active                820.0  ...            13.665986     7.0
             banned                799.5  ...            12.938776     6.0
             under review          876.0  ...            14.205184     8.0

                               video_comment_count        likes_per_view  \
                                              mean median           mean
claim_status author_ban_status
claim        active                     687.827901  286.0       0.329542
             banned                     698.402363  296.0       0.345071
             under review               698.336245  279.0       0.327997
opinion      active                       2.696609    1.0       0.219744
             banned                       2.311224    1.0       0.206868
             under review                 2.876890    1.0       0.226394

                                         comments_per_view            \
                                  median              mean    median
claim_status author_ban_status
claim        active             0.326538          0.001393  0.000776
             banned             0.358909          0.001377  0.000746
             under review       0.320867          0.001367  0.000789
opinion      active             0.218330          0.000517  0.000252
             banned             0.198483          0.000434  0.000193
             under review       0.228051          0.000536  0.000293

                               shares_per_view
                                          mean    median
claim_status author_ban_status
claim        active                   0.065456  0.049279
             banned                   0.067893  0.051606
             under review             0.065733  0.049967
opinion      active                   0.043729  0.032405
             banned                   0.040531  0.030728
             under review             0.044472  0.035027

[6 rows x 22 columns]

**Questions:**

How does the data for claim videos and opinion videos compare or differ? Consider views, comments, likes, and shares.

At this point in the investigation, what do you notice about the correlation between engagement level and claim status?

**Answers:** 

We see that all the claims videos have on average higher likes per view, higher comments per view and higher shares per view. This indicates that altogther claim videos are more viral than opinion videos. We see that eventhough claim videos have more views than opinion video the ratios between likes-comments-shares to number of views is still higher which symbolizes that they are more successful.

We see that the engagement level for claim videos is distinguishable higher than the engagement level for opinion videos

<img src="images/Construct.png" width="100" height="100" align=left>

## **PACE: Construct**

**Note**: The Construct stage does not apply to this workflow. The PACE framework can be adapted to fit the specific requirements of any project.

<img src="images/Execute.png" width="100" height="100" align=left>

## **PACE: Execute**

Consider the questions in your PACE Strategy Document and those below to craft your response.

### **Given your efforts, what can you summarize for Rosie Mae Bradshaw and the TikTok data team?**

*Note for Learners: Your answer should address TikTok's request for a summary that covers the following points:*



*   A summary of the data types of the variables
*   The minimum, mean, and maximum values for the two variables chosen

Videos can be classified into three status for our analysis, "Claim", "Opinion" and "Under Review". Videos that are categorized as "Under Review" were not taken into account for this prelimenary analysis of the correaltion between engagement levels and claim status. 

We observed that all videos categorized as claims have on average more views than opinion videos, this alone does not suggest claim videos have better engagement than opinion videos. Therefore, in order to normalize the quantities we believed are indicative of user engagement such as (# of likes) (# of comments) and (# of shares) we divided them by the number of views to that video. Therefore, if any of these ratios is too small we can conclude that the user engagement is not good. 

After perfoming this type of analysis we saw that all claim videos on average have higher likes per views, comments per views, and shares per views. This helps us conclude that these types of videos have higher user engagement.

We still want to highlight that claim videos are have more authors that have been banned than opinon video authors by almost two orders of magnitude. This means that we need to treat claim videos with lots of caution to avoid harmful authors to publish unbacked facts on their content.